version: '3.7'
services:
  eleaticsearch:
    image: elasticsearch:8.2.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:8.2.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://eleaticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - eleaticsearch
