version: '3.3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=P@$$w0rd!
      - MYSQL_USER=USR_PEON
      - MYSQL_DATABASE=PEON_db
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql-init.sql:/tmp/mysql-init.sql
    